### PR TITLE
added () to print in winpwnage.py

### PR DESCRIPTION
**Pull request by Abdur-rahmaanJ**

### CODE REVIEW

**Comment by rootm0s** [comment]
Can't really tell if you're trolling or not, I mean you only added `()` - The whole projects has to be converted to python3 if Im gonna merge PR's. Before I merge, I also need to test it.

**Comment by Abdur-rahmaanJ** [comment]
moving to py3 has many points to cover, one main point is print. fortunately this project has one issue on which you are currently working on, only in that file.

as i intend a branch for each PR, that was the only change in that branch. 

more changes on the pipeline coming

**Comment by rootm0s** [comment]
WinPwnage package is being used by Pupy framework as an external package [](https://github.com/n1nj4sec/pupy) if we convert project to python3 it will no longer work for Pupy.

**Comment by AlessandroZ** [comment]
You're right @rootm0s, if you want to upgrade it to python 3, just keep the compatibility to python 2.7 as well. 

For example, managing imports for python 2 and python 3 could be done like that: 
```
try:
    import _winreg as winreg
except ImportError:
    import winreg
```

**Comment by rootm0s** [comment]
Thanks for the input and the example @AlessandroZ

**Comment by Abdur-rahmaanJ** [comment]
that print works both for py2 and 3. ok understood the issue! and ... maybe
a new version ^^_

**Comment by rootm0s** [comment]
Will close this pull request. If you want to contribute, fork it and make all the changes needed and let me know! Cheers

**Comment by cclauss** [comment]
@Abdur-rahmaanJ Was on the right track with this PR... Small changes to make the code simultaneously compatibile with BOTH Python 2 AND Python 3.  A Big Bang port was attempted and rejected in #3.  There is no reason why this codebase could not be compatibile with both (except for the Pupy dependency might only work with legacy Python).

**Comment by Abdur-rahmaanJ** [comment]
@cclauss guess at @rootm0s' discretion

**Pull request closed without merging**
