### PR TITLE
support multiple commands

### PR DESCRIPTION
**Pull request by byehack**

### CODE REVIEW

**Comment by rootm0s** [comment]
Thanks for the PR, will check through everything when I have a little more time over. Have you tested this in a virtual machine?

**Comment by byehack** [comment]
> Thanks for the PR, will check through everything when I have a little more time over. Have you tested this in a virtual machine?

yes it worked for me.

**Comment by rootm0s** [comment]
> yes it worked for me.

Great! Also, did you test it with python2 and python3? Saw that Travis is failing for some reason.

**Comment by byehack** [comment]
> Great! Also, did you test it with python2 and python3? Saw that Travis is failing for some reason.

Travis Error:
```$ python -m pip install --upgrade pip
The command "python -m pip install --upgrade pip" failed and exited with 1 during .
Your build has been stopped.
C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/opt/bin/python.exe: No module named pip
```

i think the problem is from this travis command: `python -m pip install --upgrade pip`

**Comment by rootm0s** [comment]
> > Great! Also, did you test it with python2 and python3? Saw that Travis is failing for some reason.
> 
> Travis Error:
> 
> ```
> The command "python -m pip install --upgrade pip" failed and exited with 1 during .
> Your build has been stopped.
> C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/opt/bin/python.exe: No module named pip
> ```
> 
> i think the problem is from this travis command: `python -m pip install --upgrade pip`

Yeah, will look into it! Will merge the pr, thanks for the help. 👍 💯

**Pull request merged**
