### PR TITLE
Build winpwnage as a python package

### PR DESCRIPTION
**Pull request by AlessandroZ**
Hi @rootm0s, 

I have been very interested by your project. My goal was to integrate it to ([Pupy](https://github.com/n1nj4sec/pupy/)), another project we are working. Take a look on it, it's really cool. It's a remote shell that you can remotely load python package without writing anything on the disk. I wanted to add it as a [git submodule](https://github.com/n1nj4sec/pupy/tree/unstable/pupy/external)

However, to be loaded, the project structure as to be as a python package. That's why, I have changed the structure of your project. The goal is to load [winpwnage package](https://github.com/AlessandroZ/WinPwnage/tree/master/winpwnage) and then it could be used remotely. 
So this is what I have changed: 
- Bypass uac and the persistence functions have been [separated](https://github.com/AlessandroZ/WinPwnage/tree/master/winpwnage/functions) to be used separately on pupy. 
- Imports have been changed as `from winpwnage.core.prints import ...`
- A [constant](https://github.com/AlessandroZ/WinPwnage/blob/master/winpwnage/core/prints.py#L9) variable has been created to get the [output](https://github.com/AlessandroZ/WinPwnage/blob/master/winpwnage/core/scanner.py#L86) from pupy side.
- I have changed some python syntax to respect the PEP8 format (I hope it won't be a problem). This point will help you if one day, you will want to update to python 3 (only _winreg should be managed, and it should work on python 3) but keep the compatibility with python 2 if you do that please :)

We have already implemented [bypass uac ](https://github.com/n1nj4sec/pupy/blob/unstable/pupy/modules/bypassuac.py) and [persistence](https://github.com/n1nj4sec/pupy/blob/unstable/pupy/modules/persistence.py) modules on pupy but here the goal is that if we found bugs, or we have some issues on it, your tool will be corrected because it will be added as a submodule. 

Nothing should be different, the tool will still work outside pupy as it works right now. 

I hope you will accept this PR. Then I will take care to add it on pupy. 

Have a nice day :)

### CODE REVIEW

**Comment by rootm0s** [comment]
Hi @AlessandroZ 

I seen your project before, it's a interesting one for sure. I will review the code and test it!

When you say, if pupy find bugs, how are winpwnage gonna help out? By running different functions instead of the ones you already built-in?

**Comment by AlessandroZ** [comment]
No I wanted to say that Pupy has a community which is increasing, so people open issues on it and if it concerns winpnage, we will correct winpwnage (so your github), to fix it and not pupy because it's a git submodule. 
What I wanted to say is even we embed your project to pupy, we won't copy your code but it will be linked to your code. 

I have worked on others techniques to bypass uac such as impersonating tokens but something was missing because when I got an admin cmd, it was impossible to realize admin commands (so weird) like writing system folders or launching mimikatz. If you want to take a look to add it to winpwnage, feel free, the code is [here](https://github.com/n1nj4sec/pupy/blob/6efcf1d32c2fbb311911b0a0d86e5cfbf3d51561/pupy/packages/windows/all/pupwinutils/bypassuac_token_imp.py). 

Another thing, I forgot to mention in my PR is the possibility to add args on the payload. Take a look [here](https://github.com/AlessandroZ/WinPwnage/blob/master/winpwnage/core/utils.py#L41). Sometimes, we need to launch powershell commands with args, so I needed to add this option. 

Have a nice day.

**Comment by rootm0s** [comment]
Thanks for the explanation! Sure ill accept the PR.

I saw that, it's a good change, thanks for that!

**Comment by AlessandroZ** [comment]
Thanks, I will inform you when I will add it to pupy. I need some more free time :)

**Comment by rootm0s** [comment]
Sounds good 🔥 regarding your token impersonation issue, it's way out of my leauge lol

**Pull request merged**
