### PR TITLE
Travis CI: Which modules are imported but unused?

### PR DESCRIPTION
**Pull request by cclauss**
https://flake8.pycqa.org/en/2.5.5/warnings.html

As discussed at https://github.com/rootm0s/WinPwnage/pull/27#issuecomment-475525750

### CODE REVIEW

**Comment by rootm0s** [comment]
You need help figure out which imports we can remove?

**Comment by cclauss** [comment]
Let's leave this PR alone until after #27 lands because it removes with the __winreg__ imports.

**Comment by rootm0s** [comment]
> Let's leave this PR alone until after #27 lands because it removes with the **winreg** imports.

Alright, sounds good.

**Comment by cclauss** [comment]
Closed in favor of #34

**Pull request closed without merging**
