### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by AlessandroZ**
Here is what I have changed: 

- WMI dependency has been removed (only native ctypes called are used to create and terminate processes)
- Runas method manages parameters now, and the check for the uac level has been done earlier now. So the scan function will not always say that  this method is possible.
- cmd.exe is not needed anymore (you don't need to call using `cmd /c`). On some hardened windows, you could not launch cmd. 
- All create processes are hidden to avoid seeing a pop up. It was not always the case. 

I have tested lots of modules on win8.1 and  they all work, except this [one](https://github.com/AlessandroZ/WinPwnage/blob/master/winpwnage/functions/uac/uac_dll_mcx2prov.py), because the file is not present on my system, so I have added a [check](https://github.com/AlessandroZ/WinPwnage/blob/master/winpwnage/functions/uac/uac_dll_mcx2prov.py#L66) to not fail. 

Moreover, I suggest you to [winpwnage.py](https://github.com/rootm0s/WinPwnage/blob/master/winpwnage.py) to separate uac and persistence methods. So the user will realize a scan only for uac or for persistence. The main goal is to not use a list of continuous ID, the last ID from bypassuac is 14 and the first ID from persistence is 15. So if you want to add a new bypass uac method, you should change every IDs. I suggest you to start persistence IDs from 1. 

So you could call your tool like that: 
`./winpnwage -scan uac ` or `./winpnwage -scan persistence`

### CODE REVIEW

**Comment by rootm0s** [comment]
When I was testing all the functions on Windows 7 and Windows 10 some payloads didn't work for some reason, that's why I had to call "cmd.exe /c start CompMgmtLauncher.exe" in order for it to execute correctly and spawn a terminal. 

Are you able to test the functions on Windows 10 as well? I don't have my lab environment anymore.

**Comment by rootm0s** [comment]
Also: regarding creation of hidden processes, when i was testing i noticed that some payloads didn't show-up correctly due to the hidden process.

**Comment by AlessandroZ** [comment]
No all my tests have been done on Windows 8.1, I will try to install a Windows 10 VM to test it.

**Comment by AlessandroZ** [comment]
I have just installed a fresh win10 VM, after a scan, only the method 02, 04 and 10 was possible and all of these methods worked very well. 
If you can remove this [import](https://github.com/AlessandroZ/WinPwnage/blob/master/winpwnage/core/utils.py#L2) that I forgot, I cannot do it on this PR anymore.

**Comment by rootm0s** [comment]
> I have just installed a fresh win10 VM, after a scan, only the method 02, 04 and 10 was possible and all of these methods worked very well.
> If you can remove this [import](https://github.com/AlessandroZ/WinPwnage/blob/master/winpwnage/core/utils.py#L2) that I forgot, I cannot do it on this PR anymore.

If possible, what build numbers do you have on the Windows 10 images?
Removed the WMI import.

**Comment by AlessandroZ** [comment]
On windows 8.1, using CompMgmtLauncher, it works (you have the cmd prompt). 
The only example I have that the cmd runs on background, is using the method 08 but showing or not the process does not change anything. 

My windows build is 17134 (win10)

**Comment by rootm0s** [comment]
Tested your code now on my vm with Windows 10 (1607 build 14393) and 02,10 failed for some reason.

Windows defender flagged 08 as a threat, didn't remove anything though.

**Comment by rootm0s** [comment]
Merged your PR, thanks for all the help and ideas so far!

**Comment by AlessandroZ** [comment]
Does it finally worked ?

**Comment by rootm0s** [comment]
Everything worked except number 08 and 10. But 10 didn't work so well before either.

**Comment by AlessandroZ** [comment]
The method 08 won't prompt anything but you can see the cmd.exe launched on background (check it, using process explorer). For the method 10, it's weird, it worked for me.

Have a nice day. Thanks for the merge.

**Pull request merged**
