### PR TITLE
Travis CI: Prove that running winpwnage.py fails on Python 3

### LINKED ISSUE #25: Travis CI currently builds the app but does not run it
Perhaps it would be a good idea to add a command to the end of the __.travis.yml__ file that ___runs___ the app.
* Does it run as expected in Python 2?
* Does it run as expected in Python 3?

### PR DESCRIPTION
**Pull request by cclauss**
Fixes #25

### CODE REVIEW

**Comment by rootm0s** [comment]
Why should it test python3 when it's not fully ported yet?

**Comment by cclauss** [comment]
It is begging for someone to add a test(s) that ___prove___ that it is not ported to Python 3.  If they can do that then they have earned the right to add back the __allow_failures__.

**Comment by cclauss** [comment]
This PR so now does __python winpwnage__ and proves that the port to Python 3 is not yet complete.

**Comment by cclauss** [comment]
Closing in favor of #27

**Pull request closed without merging**
