### PR TITLE
Simplify using bool(), dict.items(), dict.get()

### PR DESCRIPTION
**Pull request by cclauss**
Ready for review.

### CODE REVIEW

**Comment by cclauss** [comment]
Ready for review.

**Comment by rootm0s** [comment]
[d60d2e7](https://github.com/rootm0s/WinPwnage/pull/31/commits/d60d2e7a7de7cb8e5157fbc47b0672ce625fa86f) - Does not contain, the python3 and python2 winreg import. Never used to return bool, doesnt even know what it does and why it can't just return True!

**Comment by cclauss** [comment]
Rebased on current master.

The goal of this PR was to remove 23 lines of unnecessary code.  [__bool()__](https://docs.python.org/3/library/functions.html#bool) converts any value to either True or False.  Here we use bool() as a signal to the reader that we are only going to return one of those two values.

**Comment by rootm0s** [comment]
Much appreciated for the explanation! Merging

**Pull request merged**
