### PR TITLE
WinPwnage runs on both Python 2 and Python 3

### LINKED ISSUE #25: Travis CI currently builds the app but does not run it
Perhaps it would be a good idea to add a command to the end of the __.travis.yml__ file that ___runs___ the app.
* Does it run as expected in Python 2?
* Does it run as expected in Python 3?

### PR DESCRIPTION
**Pull request by cclauss**
Fixes #25

https://travis-ci.com/rootm0s/WinPwnage/jobs/186762437#L93
WinPwnage runs on Python 3

### CODE REVIEW

**Comment by rootm0s** [comment]
A thought, since I made all the functions to use the registry functions inside `utils.py`we can actually just remove the `_winreg` imports from all the files that uses registry functions and just import utils.

**Comment by cclauss** [comment]
#32 helped us to finde unused imports so that makes things cleaner.

**Comment by cclauss** [comment]
Can you please do me a favor and turn on ___Auto cancel pull request builds___ on https://github.com/rootm0s/WinPwnage/settings ? This will halt the testing of older commits when a new commit is made on the same PR.

Auto cancel pull request builds

**Comment by rootm0s** [comment]
> Can you please do me a favor and turn on _**Auto cancel pull request builds**_ on https://github.com/rootm0s/WinPwnage/settings ? This will halt the testing of older commits when a new commit is made on the same PR.

Done!

**Comment by rootm0s** [comment]
Let me know when i should push PR's

**Comment by cclauss** [comment]
This one is ready for review.

**Comment by rootm0s** [comment]
Looks good

**Pull request merged**
