### PR TITLE
scanner() and function() only take a single str parameter

### PR DESCRIPTION
**Pull request by cclauss**
In __scanner.py__:
Line 61: Rename functions to function_groups
line 125 and 142: Do not pass in a bool for each function_group but instead tell us the one function_group you want
line 134 and 149: Do a dict lookup (__function_groups[self.function_group]__) to get info for the functions in that function_group

The dict lookup allows us to remove a bunch of code and dedent the code below it.

Once __scanner()__ and __function()__ only take a single str parameter we can simplify __main()__ as well.

### CODE REVIEW

**Comment by rootm0s** [comment]
It's a good change, but added removal of `sys.argv` to the todo list, think argparse would be a better choice. Has this been tested with `-use`?

**Comment by cclauss** [comment]
If you provide me with a few more __use__ commands, I will add more test runs.

**Comment by rootm0s** [comment]
> If you provide me with a few more **use** commands, I will add more test runs.
They will most likely not work since last test using Travis failed, gonna have to test each function manually or start using appveyor I guess

**Comment by rootm0s** [comment]
@cclauss examples ^

**Comment by cclauss** [comment]
Which way should we go?  https://realpython.com/comparing-python-command-line-parsing-libraries-argparse-docopt-click/

**Comment by rootm0s** [comment]
We go with core, so we don't need any unnecessary external packages. So the logical reason would be to go for argparse

**Pull request closed without merging**
